### ISSUE TITLE
Build From Source install  error

### ISSUE THREAD

**Issue by 1412kauti** [wiiznokes/fan-control#102]
I was using the build instructions provided

```
git clone https://github.com/wiiznokes/fan-control.git
cd fan-control
sudo apt install make bison flex clang -y
just libsensors
cargo run --release
```
Things were perfect till the last step
`cargo run --release`

The error I got is
```
❯ cargo run --release
   Compiling sensors-sys v0.2.12
   Compiling fluent-langneg v0.13.0
   Compiling intl_pluralrules v7.0.2
   Compiling ouroboros_macro v0.17.2
   Compiling dirs v5.0.1
   Compiling darling_core v0.20.8
   Compiling iced_style v0.12.0 (https://github.com/pop-os/libcosmic?branch=master#61a14a95)
   Compiling self_cell v0.10.3
   Compiling wayland-protocols-plasma v0.2.0
   Compiling tempfile v3.10.1
   Compiling xkbcommon-dl v0.4.2
   Compiling fluent-syntax v0.11.0
   Compiling crossbeam-channel v0.5.12
   Compiling filetime v0.2.23
   Compiling xdg v2.5.2
   Compiling equivalent v1.0.1
   Compiling utf8parse v0.2.1
   Compiling unicode-xid v0.2.4
   Compiling cargo-packager-resource-resolver v0.1.0
   Compiling derive_more-impl v1.0.0-beta.6
   Compiling notify v6.1.1
   Compiling anstyle-parse v0.2.3
   Compiling indexmap v2.2.6
   Compiling fluent-bundle v0.15.2
   Compiling atomicwrites v0.4.2 (https://github.com/jackpot51/rust-atomicwrites#043ab485)
   Compiling ordered-multimap v0.7.1
   Compiling num-rational v0.4.1
   Compiling cached_proc_macro v0.20.0
   Compiling fluent v0.16.0
   Compiling num_enum v0.7.2
   Compiling iced_renderer v0.12.0 (https://github.com/pop-os/libcosmic?branch=master#61a14a95)
   Compiling parking_lot v0.12.1
   Compiling rust-embed-utils v8.3.0
   Compiling ouroboros_macro v0.18.3
   Compiling num-iter v0.1.44
   Compiling ouroboros v0.17.2
   Compiling winit v0.29.10 (https://github.com/pop-os/winit.git?branch=winit-0.29#bdc66109)
   Compiling rust-embed v8.3.0
   Compiling ron v0.8.1
   Compiling cargo-packager-utils v0.1.0
   Compiling unicode-normalization v0.1.23
   Compiling cosmic-config-derive v0.1.0 (https://github.com/pop-os/libcosmic?branch=master#61a14a95)
   Compiling serde_spanned v0.6.5
   Compiling toml_datetime v0.6.5
   Compiling num-complex v0.4.5
   Compiling instant v0.1.12
   Compiling cached_proc_macro_types v0.1.1
   Compiling arc-swap v1.7.1
   Compiling serde_json v1.0.115
   Compiling anstyle-query v1.0.2
   Compiling darling_macro v0.20.8
   Compiling signal-hook v0.3.17
   Compiling winnow v0.6.5
   Compiling anstyle v1.0.6
   Compiling colorchoice v1.0.0
   Compiling heck v0.4.1
   Compiling utils v0.1.0 (/home/kaito/Documents/GitHub/fan-control/utils)
   Compiling cosmic-config v0.1.0 (https://github.com/pop-os/libcosmic?branch=master#61a14a95)
   Compiling anstream v0.6.13
   Compiling ouroboros v0.18.3
   Compiling num v0.4.1
   Compiling i18n-embed v0.14.1
   Compiling idna v0.5.0
   Compiling cached v0.49.3
   Compiling derive_more v1.0.0-beta.6
   Compiling darling v0.20.8
   Compiling iced_widget v0.12.0 (https://github.com/pop-os/libcosmic?branch=master#61a14a95)
   Compiling lm-sensors v0.2.0 (https://github.com/wiiznokes/lm-sensors.git?branch=pwm#bc9f27df)
   Compiling rust-ini v0.20.0
   Compiling locale_config v0.3.0
   Compiling dashmap v5.5.3
   Compiling form_urlencoded v1.2.1
   Compiling csscolorparser v0.6.2
   Compiling any_ascii v0.1.7
   Compiling iced_winit v0.12.0 (https://github.com/pop-os/libcosmic?branch=master#61a14a95)
   Compiling toml_edit v0.22.9
   Compiling grid v0.11.0
   Compiling itoa v1.0.11
   Compiling almost v0.2.0
   Compiling iana-time-zone v0.1.60
   Compiling ryu v1.0.17
   Compiling chrono v0.4.37
   Compiling taffy v0.3.11 (https://github.com/DioxusLabs/taffy?rev=7781c70#7781c702)
   Compiling cosmic-theme v0.1.0 (https://github.com/pop-os/libcosmic?branch=master#61a14a95)
   Compiling lexical-sort v0.3.1
   Compiling iced v0.12.0 (https://github.com/pop-os/libcosmic?branch=master#61a14a95)
   Compiling toml v0.8.12
   Compiling i18n-embed-fl v0.8.0
   Compiling url v2.5.0
   Compiling hardware v0.1.0 (/home/kaito/Documents/GitHub/fan-control/hardware)
   Compiling freedesktop-icons v0.2.6
   Compiling derive_setters v0.1.6
   Compiling fraction v0.14.0
   Compiling directories v5.0.1
   Compiling winres v0.1.12
   Compiling light_enum v0.2.2
   Compiling heck v0.5.0
   Compiling clap_lex v0.7.0
   Compiling css-color v0.2.8
   Compiling strsim v0.11.0
   Compiling apply v0.3.0
   Compiling libcosmic v0.1.0 (https://github.com/pop-os/libcosmic?branch=master#61a14a95)
   Compiling clap_builder v4.5.2
   Compiling data v0.1.0 (/home/kaito/Documents/GitHub/fan-control/data)
   Compiling clap_derive v4.5.4
   Compiling fan-control v0.1.3 (/home/kaito/Documents/GitHub/fan-control)
   Compiling signal-hook-mio v0.2.3
   Compiling env_filter v0.1.0
   Compiling humantime v2.1.0
   Compiling crossterm v0.27.0
   Compiling env_logger v0.11.3
   Compiling clap v4.5.4
   Compiling ui v0.1.0 (/home/kaito/Documents/GitHub/fan-control/ui)
    Finished release [optimized] target(s) in 21.15s
     Running `target/release/fan-control`
thread 'main' panicked at /home/kaito/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/61a14a9/iced/tiny_skia/src/window/compositor.rs:56:10:
Create softbuffer surface for window: PlatformError(Some("Visual 0x23 does not use softbuffer's pixel format and is unsupported"), None)
stack backtrace:
   0:           0xdda61c - std::backtrace_rs::backtrace::libunwind::trace::ha637c64ce894333a
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:           0xdda61c - std::backtrace_rs::backtrace::trace_unsynchronized::h47f62dea28e0c88d
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:           0xdda61c - std::sys_common::backtrace::_print_fmt::h9eef0abe20ede486
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:67:5
   3:           0xdda61c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hed7f999df88cc644
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:44:22
   4:           0xe09bb0 - core::fmt::rt::Argument::fmt::h1539a9308b8d058d
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/rt.rs:142:9
   5:           0xe09bb0 - core::fmt::write::h3a39390d8560d9c9
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/mod.rs:1120:17
   6:           0xdd6acf - std::io::Write::write_fmt::h5fc9997dfe05f882
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/io/mod.rs:1762:15
   7:           0xdda404 - std::sys_common::backtrace::_print::h894006fb5c6f3d45
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:47:5
   8:           0xdda404 - std::sys_common::backtrace::print::h23a2d212c6fff936
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:34:9
   9:           0xddbbb7 - std::panicking::default_hook::{{closure}}::h8a1d2ee00185001a
  10:           0xddb91f - std::panicking::default_hook::h6038f2eba384e475
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:292:9
  11:           0xddc038 - std::panicking::rust_panic_with_hook::h2b5517d590cab22e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:779:13
  12:           0xddbf1e - std::panicking::begin_panic_handler::{{closure}}::h233112c06e0ef43e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:657:13
  13:           0xddaae6 - std::sys_common::backtrace::__rust_end_short_backtrace::h6e893f24d7ebbff8
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:170:18
  14:           0xddbc82 - rust_begin_unwind
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
  15:           0x44c7c5 - core::panicking::panic_fmt::hbf0e066aabfa482c
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
  16:           0x44cd03 - core::result::unwrap_failed::hddb4fea594200c52
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
  17:           0x4a5807 - <iced_renderer::compositor::Compositor as iced_graphics::compositor::Compositor>::create_surface::h4ddb07ea1ff2a7de
  18:           0x46abf6 - iced_winit::multi_window::window_manager::WindowManager<A,C>::insert::hf2dffbdaf985aa7b
  19:           0x46bcbc - iced_winit::multi_window::run::h8ed211e9c274ec9a
  20:           0x4d57fe - fan_control::main::habec4908fa0ca0f9
  21:           0x52c9d3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h870f6cd08cd5517e
  22:           0x5676d9 - std::rt::lang_start::{{closure}}::h9fcbd6db6c295ab4
  23:           0xdcd507 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hd95060ecd5e1ca24
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:284:13
  24:           0xdcd507 - std::panicking::try::do_call::h6e8cf51db32a6e4b
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  25:           0xdcd507 - std::panicking::try::h3a52eefe24fe3c29
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  26:           0xdcd507 - std::panic::catch_unwind::h24c28c23c02c3841
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  27:           0xdcd507 - std::rt::lang_start_internal::{{closure}}::h705d3c9cbc06ef47
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:48
  28:           0xdcd507 - std::panicking::try::do_call::ha21f52ba13158470
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  29:           0xdcd507 - std::panicking::try::h5581346bf6aeb1f8
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  30:           0xdcd507 - std::panic::catch_unwind::h7919645a6b72e25b
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  31:           0xdcd507 - std::rt::lang_start_internal::h12de51168669836e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:20
  32:           0x5676ce - std::rt::lang_start::h236675407cae54ea
  33:     0x7b74a3229d90 - <unknown>
  34:     0x7b74a3229e40 - __libc_start_main
  35:           0x44d435 - _start
  36:                0x0 - <unknown>
[ERROR hardware::linux] can't set auto to a pwm sensor when quitting: sensors_set_value() failed: [4] Kernel interface error
[ERROR hardware::linux] can't set auto to a pwm sensor when quitting: sensors_set_value() failed: [4] Kernel interface error
[ERROR hardware::linux] can't set auto to a pwm sensor when quitting: sensors_set_value() failed: [4] Kernel interface error
[ERROR hardware::linux] can't set auto to a pwm sensor when quitting: sensors_set_value() failed: [4] Kernel interface error

```
I'm not familiar with Rust...a little help plz

**Comment by wiiznokes** [comment]
This is a runtime error. The same of #98 .

I don't think it can be fixed but i have some question that might help

- are you running wayland ?
- what DE do you use and which version / Linux distrib (`neofetch`)

You could try to modify `ui/Cargo.toml`, and uncomment `#"wgpu",`, ei, change to `"wgpu",` and rerun `cargo run`.

Also, have you installed the udev rules ?

**Comment by 1412kauti** [comment]
Hey!...
Im using PopOS22.04 Default DE...not the new Cosmic DE 
No wayland....

Editting the Cargo.toml worked...thankx
