### ISSUE TITLE
error on windows

### ISSUE THREAD

**Issue by wiiznokes** [wiiznokes/fan-control#21]
```
PS C:\Users\wiiz\Documents\fan-control> cargo run --release
   Compiling data v0.1.0 (C:\Users\wiiz\Documents\fan-control\data)
   Compiling ui v0.1.0 (C:\Users\wiiz\Documents\fan-control\ui)
   Compiling fan-control v0.1.0 (C:\Users\wiiz\Documents\fan-control)
    Finished release [optimized] target(s) in 9.09s
     Running `target\release\fan-control.exe`
[LHM] Server Started on 127.0.0.1:55555
[LHM] Client accepted!
[LHM] nbControl: 9
[LHM] nbFan: 9
[LHM] nbTemp: 4
[LHM] Sending hardware
Unhandled exception. System.IO.IOException: Unable to write data to the transport connection: Une connexion établie a été abandonnée par un logiciel de votre ordinateur hôte..
 ---> System.Net.Sockets.SocketException (10053): Une connexion établie a été abandonnée par un logiciel de votre ordinateur hôte.
   at System.Net.Sockets.NetworkStream.Write(ReadOnlySpan`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(ReadOnlySpan`1 buffer)
   at LibreHardwareMonitorWrapper.Server.SendHardware(String jsonText) in C:\Users\wiiz\Documents\fan-control\hardware\LibreHardwareMonitorWrapper\Server.cs:line 40
   at Program.<Main>$(String[] args) in C:\Users\wiiz\Documents\fan-control\hardware\LibreHardwareMonitorWrapper\Program.cs:line 8
   at Program.<Main>(String[] args)
```

**Comment by wiiznokes** [comment]
second run works with no problem
